### PR TITLE
fixes #27

### LINKED ISSUE #27: Bugs in /getTopUsers endpoint
Based on a question from the Web team on slack, I investigated and noticed two bugs in our `/getTopUsers` endpoint:

1. It returns HTTP 500 if wrong input param is passed in e.g "Favs" instead of "favs", as in https://hist-favs-checkout.herokuapp.com/getTopUsers?selected=Favs&page=0&nums=10. We should have an ending else clause just before this [line](https://github.com/usfcs-perf-eng-s20/heroku-project-favs/blob/master/src/cs/usfca/edu/histfavcheckout/controller/HistFavCheckoutHandler.java#L171) and return a 400 BAD REQUEST from there. 
2. It returns HTTP 500 if data doesn't exist for page range e.g currently page=1&nums=10. You can test this by calling the url: https://hist-favs-checkout.herokuapp.com/getTopUsers?selected=favs&page=1&nums=10

**NOTE:** These errors only occur when the config is set to use external services. If you disable using external services, you won't get these errors. So try to test with this condition when to reproduce the error.

### PR DESCRIPTION
**Pull request by kedarkhetia**
Note: Added fix for the bug in API client too.

Verify fix by calling below two endpoints,

1. https://hist-fav-checkout-beta.herokuapp.com//getTopUsers?selected=Favs&page=0&nums=10
2. https://hist-fav-checkout-beta.herokuapp.com//getTopUsers?selected=favs&page=1&nums=10

### CODE REVIEW

File: src/cs/usfca/edu/histfavcheckout/controller/HistFavCheckoutHandler.java [hunk 1]
```diff
@@ -168,17 +168,23 @@ else if(selected.equals("favs")) {
...
+			for(TopUser topUser : users) {
+				topUserMap.put(topUser.getUserId(), topUser);
+			}
+			List<UserInfoResponse.UserInfo> userInfos = APIClient.getTopUsers(topUserMap.keySet());
+			for(UserInfoResponse.UserInfo userInfo : userInfos) {
+				response.add(new TopUserResponse(userInfo.getUserName(), 
+						userInfo.getEmail(), topUserMap.get(userInfo.getUserId()).getFavsCount(), 
+						topUserMap.get(userInfo.getUserId()).getCheckoutsCount(),
+						topUserMap.get(userInfo.getUserId()).getRatingsCount()));
+			}
```
Comment (mosopeogundipe) [inline src/cs/usfca/edu/histfavcheckout/controller/HistFavCheckoutHandler.java]: Nice work overall! Just wanted to point out something I noticed while testing.
I tried the url: https://hist-fav-checkout-beta.herokuapp.com/getTopUsers?selected=favs&page=0&nums=10

And I get back the response:
```
[
    {
        "userName": "nat",
        "email": "nat@gmail.com",
        "favsCount": 0,
        "checkoutsCount": 2,
        "ratingsCount": 1
    },
    {
        "userName": "testUser1",
        "email": "test1@hotmail.com",
        "favsCount": 1,
        "checkoutsCount": 1,
        "ratingsCount": 0
    },
    {
        "userName": "testUser4",
        "email": "test4@hotmail.com",
        "favsCount": 1,
        "checkoutsCount": 0,
        "ratingsCount": 0
    },
    {
        "userName": "testUser24",
        "email": "test24@hotmail.com",
        "favsCount": 0,
        "checkoutsCount": 0,
        "ratingsCount": 1
    },
    {
        "userName": "testUser46",
        "email": "test46@hotmail.com",
        "favsCount": 0,
        "checkoutsCount": 0,
        "ratingsCount": 1
    }
]
```

So the output isn't ordered by Favs count anymore because the first element has FavsCount of 0 and the next two elements have FavCount of 1.

I think this has something to do with line [182](https://github.com/usfcs-perf-eng-s20/heroku-project-favs/pull/28/files#diff-0fae860ae0c1e35be827d26bc884c318R182). The response coming back from User API is probably not in the same order as we expect, so it messes up the ordering.

I honestly haven't come up with a good approach to solve this too, but just wanted to mention the issue.

**Review by mosopeogundipe — CHANGES_REQUESTED** [review]

File: src/cs/usfca/edu/histfavcheckout/controller/HistFavCheckoutHandler.java (hunk 1 above)
Comment (kedarkhetia) [reply src/cs/usfca/edu/histfavcheckout/controller/HistFavCheckoutHandler.java]: Yes, I agree. It looks like Login team do not maintain the order. I have updated the CR accordingly and tested.

**Review by mosopeogundipe — APPROVED** [review]
Looks good to me!
